"""
Microsoft Teams provider tests.

Every Microsoft Graph call is monkeypatched: no real credentials, no network
access, and no fabricated Teams data.
"""

import pytest
import requests

from providers.base import (
    ProviderAPIError,
    ProviderConsentRequiredError,
    ProviderTokenExpiredError,
    TranscriptUnavailableError,
)
from providers.ms_teams import MSTeamsProvider
from providers.session_tokens import TokenSet, call_with_refresh


JOIN_URL = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_abc%40thread.v2/0"

VTT_SAMPLE = """WEBVTT

NOTE Meeting transcript generated by Microsoft Teams

00:00:01.000 --> 00:00:04.000
<v Sarah Khan>Support volume is up 30% this quarter.</v>

00:00:05.000 --> 00:00:09.000
<v Priya>We need email notifications
when refund status changes.</v>

00:00:10.000 --> 00:00:12.000
<v Priya>Rahul can scope it.</v>
"""


@pytest.fixture
def provider(monkeypatch):
    monkeypatch.setenv("AZURE_CLIENT_ID", "mock-azure-client-id")
    monkeypatch.setenv("AZURE_TENANT_ID", "mock-tenant-id")
    monkeypatch.setenv("AZURE_CLIENT_SECRET", "mock-azure-client-secret")
    return MSTeamsProvider()


class FakeResponse:
    def __init__(self, body=None, status_code=200, text="", headers=None):
        self.status_code = status_code
        self._body = body
        self.text = text
        self.headers = headers or {}

    def json(self):
        if self._body is None:
            raise ValueError("no JSON body")
        return self._body


def events_response(subject="Refund Dashboard Review", join_url=JOIN_URL, include_online_meeting=True):
    event = {
        "id": "event-1",
        "subject": subject,
        "isOnlineMeeting": True,
        "start": {"dateTime": "2026-08-20T09:00:00.0000000", "timeZone": "UTC"},
        "end": {"dateTime": "2026-08-20T10:00:00.0000000", "timeZone": "UTC"},
        "organizer": {"emailAddress": {"name": "Sarah Khan", "address": "sarah@example.com"}},
        "attendees": [
            {"emailAddress": {"name": "Priya Nair", "address": "priya@example.com"}},
            {"emailAddress": {"name": "Rahul Mehta", "address": "rahul@example.com"}},
        ],
    }
    if include_online_meeting:
        event["onlineMeeting"] = {"joinUrl": join_url}
    return FakeResponse({"value": [event]})


# --- Configuration and authorization URL ---

def test_authorization_url_uses_the_tenant_and_carries_pkce(provider):
    url = provider.get_authorization_url(
        "http://localhost:8501",
        state="signed.state.value",
        code_challenge="challenge-abc",
        code_challenge_method="S256",
    )

    assert "login.microsoftonline.com/mock-tenant-id/oauth2/v2.0/authorize" in url
    assert "state=signed.state.value" in url
    assert "code_challenge=challenge-abc" in url
    assert "code_challenge_method=S256" in url
    assert "mock-azure-client-secret" not in url


def test_requested_scopes_are_delegated_and_least_privileged(provider):
    url = provider.get_authorization_url("http://localhost:8501", state="s")

    # OnlineMeetingTranscript.Read.All is the narrowest delegated permission Graph
    # offers for reading transcripts; Calendars.Read is what discovery needs.
    assert "OnlineMeetingTranscript.Read.All" in url
    assert "Calendars.Read" in url
    assert "offline_access" in url
    # Application-only permissions must never be requested on a delegated flow.
    assert "OnlineMeetingTranscript.Read.Chat" not in url
    assert ".default" not in url


def test_setup_instructions_name_variables_only_and_state_admin_consent(provider):
    instructions = provider.get_setup_instructions()

    assert "Microsoft Entra ID" in instructions
    assert "AZURE_CLIENT_ID" in instructions
    assert "admin consent" in instructions.lower()
    # Names only — never the configured values.
    assert "mock-azure-client-id" not in instructions
    assert "mock-azure-client-secret" not in instructions
    assert "mock-tenant-id" not in instructions


# --- Meeting resolution ---

def test_meeting_is_resolved_by_join_url_filter(provider, monkeypatch):
    captured = {}

    def fake_get(url, *args, **kwargs):
        captured["url"] = url
        return FakeResponse({"value": [{"id": "meeting-1", "subject": "Refund Dashboard Review"}]})

    monkeypatch.setattr(requests, "get", fake_get)

    meeting = provider.resolve_meeting_by_join_url(JOIN_URL, access_token="at-1")

    assert meeting["id"] == "meeting-1"
    # Graph v1.0 has no list-all endpoint for delegated callers; the JoinWebUrl
    # filter is the supported lookup, and the URL must be encoded in the literal.
    assert "/me/onlineMeetings?$filter=JoinWebUrl%20eq%20'" in captured["url"]
    assert "https%3A%2F%2Fteams.microsoft.com" in captured["url"]


def test_unresolvable_join_url_is_reported(provider, monkeypatch):
    monkeypatch.setattr(requests, "get", lambda *a, **kw: FakeResponse({"value": []}))

    with pytest.raises(TranscriptUnavailableError, match="no online meeting for that join URL"):
        provider.resolve_meeting_by_join_url(JOIN_URL, access_token="at-1")


def test_non_url_input_is_rejected_before_any_request(provider, monkeypatch):
    def boom(*args, **kwargs):
        raise AssertionError("no request should be made")

    monkeypatch.setattr(requests, "get", boom)

    with pytest.raises(Exception, match="Teams join URL"):
        provider.resolve_meeting_by_join_url("not-a-url", access_token="at-1")


# --- Calendar-based discovery ---

def test_discovery_walks_calendar_events_to_transcripts(provider, monkeypatch):
    calls = []

    def fake_get(url, *args, **kwargs):
        calls.append((url, dict(kwargs.get("params") or {})))
        if "/transcripts" in url:
            return FakeResponse({"value": [
                {"id": "transcript-1", "createdDateTime": "2026-08-20T10:05:00Z",
                 "endDateTime": "2026-08-20T10:00:00Z"}
            ]})
        if "/onlineMeetings" in url:
            return FakeResponse({"value": [{"id": "meeting-1", "joinWebUrl": JOIN_URL}]})
        return events_response()

    monkeypatch.setattr(requests, "get", fake_get)

    result = provider.discover_transcripts(access_token="at-1")
    entries = result["transcripts"]

    assert len(entries) == 1
    entry = entries[0]
    assert entry["id"] == "meeting-1/transcripts/transcript-1"
    # Title and date come from the real calendar event / transcript resource.
    assert entry["title"] == "Refund Dashboard Review"
    assert entry["date"] == "2026-08-20T10:05:00Z"
    assert entry["source_type"] == "ms_graph_transcript"
    assert entry["available"] is True
    assert entry["details"]["organizer"] == "Sarah Khan"
    assert "Priya Nair" in entry["participants"]

    events_call = next(c for c in calls if c[0].endswith("/me/events"))
    params = events_call[1]
    assert params["$filter"] == "isOnlineMeeting eq true"
    # Graph rejects some filter+sort combinations on /me/events, so ordering is
    # done client-side rather than with $orderby.
    assert "$orderby" not in params
    assert "onlineMeeting" in params["$select"]


def test_discovery_skips_events_without_a_join_url_and_explains_why(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if "/me/events" in url:
            return events_response(include_online_meeting=False)
        raise AssertionError("no meeting lookup should happen without a join URL")

    monkeypatch.setattr(requests, "get", fake_get)

    result = provider.discover_transcripts(access_token="at-1")

    assert result["transcripts"] == []
    assert any("no Teams join URL" in note for note in result["notes"])


def test_discovery_reports_meetings_without_transcripts(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if "/transcripts" in url:
            return FakeResponse({"value": []})
        if "/onlineMeetings" in url:
            return FakeResponse({"value": [{"id": "meeting-1"}]})
        return events_response()

    monkeypatch.setattr(requests, "get", fake_get)

    result = provider.discover_transcripts(access_token="at-1")
    assert result["transcripts"] == []


def test_discovery_reports_no_online_meeting_events(provider, monkeypatch):
    monkeypatch.setattr(requests, "get", lambda *a, **kw: FakeResponse({"value": []}))

    result = provider.discover_transcripts(access_token="at-1")

    assert result["transcripts"] == []
    assert any("no calendar events" in note.lower() for note in result["notes"])


def test_discovery_follows_odata_next_link(provider, monkeypatch):
    urls = []

    def fake_get(url, *args, **kwargs):
        urls.append(url)
        if "/transcripts" in url:
            return FakeResponse({"value": []})
        if "/onlineMeetings" in url:
            return FakeResponse({"value": [{"id": "meeting-1"}]})
        if "skiptoken" in url:
            return FakeResponse({"value": [{
                "id": "event-2", "subject": "Older Sync", "isOnlineMeeting": True,
                "onlineMeeting": {"joinUrl": JOIN_URL},
                "start": {"dateTime": "2026-08-01T09:00:00.0000000"},
            }]})
        body = events_response().json()
        body["@odata.nextLink"] = "https://graph.microsoft.com/v1.0/me/events?$skiptoken=abc"
        return FakeResponse(body)

    monkeypatch.setattr(requests, "get", fake_get)

    provider.discover_transcripts(access_token="at-1")

    assert any("skiptoken" in u for u in urls)


def test_discovery_reports_probe_limit_instead_of_silently_capping(provider, monkeypatch):
    events = [
        {
            "id": f"event-{i}",
            "subject": f"Sync {i}",
            "isOnlineMeeting": True,
            "onlineMeeting": {"joinUrl": JOIN_URL},
            "start": {"dateTime": f"2026-08-0{i + 1}T09:00:00.0000000"},
        }
        for i in range(4)
    ]

    def fake_get(url, *args, **kwargs):
        if "/transcripts" in url:
            return FakeResponse({"value": []})
        if "/onlineMeetings" in url:
            return FakeResponse({"value": [{"id": "meeting-1"}]})
        return FakeResponse({"value": events})

    monkeypatch.setattr(requests, "get", fake_get)

    result = provider.discover_transcripts(access_token="at-1", event_probe_limit=2)

    assert result["truncated"] is True
    assert any("2 most recent of 4" in note for note in result["notes"])


def test_discovery_raises_the_permission_error_when_nothing_was_retrievable(provider, monkeypatch):
    """An empty list would hide a consent problem; the user must see the real reason."""
    def fake_get(url, *args, **kwargs):
        if "/onlineMeetings" in url:
            return FakeResponse(
                {"error": {"code": "Authorization_RequestDenied",
                           "message": "Insufficient privileges to complete the operation."}},
                status_code=403,
            )
        return events_response()

    monkeypatch.setattr(requests, "get", fake_get)

    with pytest.raises(ProviderConsentRequiredError, match="admin consent"):
        provider.discover_transcripts(access_token="at-1")


def test_discovery_propagates_expired_token(provider, monkeypatch):
    monkeypatch.setattr(
        requests, "get",
        lambda *a, **kw: FakeResponse(
            {"error": {"code": "InvalidAuthenticationToken", "message": "Access token has expired."}},
            status_code=401,
        ),
    )

    with pytest.raises(ProviderTokenExpiredError):
        provider.discover_transcripts(access_token="expired-token")


# --- VTT parsing ---

def test_vtt_parsing_extracts_speakers_and_merges_multiline_cues(provider):
    text, speakers = provider.parse_vtt(VTT_SAMPLE)

    assert speakers == ["Sarah Khan", "Priya"]
    assert "Sarah Khan: Support volume is up 30% this quarter." in text
    # A cue split across lines must be rejoined into one utterance.
    assert "Priya: We need email notifications when refund status changes." in text
    assert "WEBVTT" not in text
    assert "NOTE" not in text
    assert "-->" not in text
    # Consecutive cues from the same speaker are joined without relabelling.
    assert text.count("Priya:") == 1
    assert "Rahul can scope it." in text


def test_vtt_parsing_handles_a_transcript_without_voice_tags(provider):
    plain_vtt = (
        "WEBVTT\n\n"
        "00:00:01.000 --> 00:00:03.000\n"
        "Sarah: Refund SLA must be 24 hours.\n"
    )
    text, speakers = provider.parse_vtt(plain_vtt)

    assert "Sarah: Refund SLA must be 24 hours." in text
    assert speakers == ["Sarah"]


def test_vtt_parsing_never_invents_a_speaker(provider):
    anonymous_vtt = (
        "WEBVTT\n\n"
        "00:00:01.000 --> 00:00:03.000\n"
        "The team agreed to build a refund dashboard.\n"
    )
    text, speakers = provider.parse_vtt(anonymous_vtt)

    assert speakers == []
    assert text.strip() == "The team agreed to build a refund dashboard."


def test_vtt_parsing_of_empty_content_returns_nothing(provider):
    text, speakers = provider.parse_vtt("WEBVTT\n\n")
    assert text == ""
    assert speakers == []


# --- Transcript retrieval ---

def test_get_transcript_requests_vtt_and_normalizes_it(provider, monkeypatch):
    requested = []

    def fake_get(url, *args, **kwargs):
        requested.append((url, dict(kwargs.get("params") or {}), dict(kwargs.get("headers") or {})))
        if url.endswith("/content"):
            return FakeResponse(status_code=200, text=VTT_SAMPLE,
                                headers={"Content-Type": "text/vtt"})
        return FakeResponse({"id": "transcript-1", "createdDateTime": "2026-08-20T10:05:00Z"})

    monkeypatch.setattr(requests, "get", fake_get)

    transcript = provider.get_transcript(
        "meeting-1/transcripts/transcript-1",
        access_token="at-1",
        meeting_title="Refund Dashboard Review",
    )

    assert transcript.source == "microsoft_teams"
    assert transcript.provider == "microsoft_teams"
    assert transcript.transcript_id == "meeting-1/transcripts/transcript-1"
    assert transcript.metadata["transcript_id"] == "transcript-1"
    assert transcript.meeting_title == "Refund Dashboard Review"
    assert transcript.meeting_date == "2026-08-20T10:05:00Z"
    assert transcript.participants == ["Sarah Khan", "Priya"]
    assert transcript.metadata["content_format"] == "text/vtt"
    assert transcript.metadata["speaker_attributed"] is True
    assert transcript.metadata["online_meeting_id"] == "meeting-1"
    assert transcript.metadata["meeting_resource"] == "meeting-1/transcripts/transcript-1"

    content_call = next(c for c in requested if c[0].endswith("/content"))
    assert content_call[1].get("$format") == "text/vtt"
    assert content_call[2].get("Accept") == "text/vtt"


def test_get_transcript_picks_the_newest_when_only_a_meeting_id_is_given(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if url.endswith("/content"):
            return FakeResponse(status_code=200, text=VTT_SAMPLE,
                                headers={"Content-Type": "text/vtt"})
        if url.endswith("/transcripts"):
            return FakeResponse({"value": [
                {"id": "older", "createdDateTime": "2026-08-01T10:00:00Z"},
                {"id": "newest", "createdDateTime": "2026-08-20T10:00:00Z"},
            ]})
        return FakeResponse({"id": "newest", "createdDateTime": "2026-08-20T10:00:00Z"})

    monkeypatch.setattr(requests, "get", fake_get)

    transcript = provider.get_transcript("meeting-1", access_token="at-1")
    assert transcript.metadata["transcript_id"] == "newest"


def test_get_transcript_accepts_a_join_url(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if url.endswith("/content"):
            return FakeResponse(status_code=200, text=VTT_SAMPLE,
                                headers={"Content-Type": "text/vtt"})
        if url.endswith("/transcripts"):
            return FakeResponse({"value": [{"id": "transcript-1",
                                            "createdDateTime": "2026-08-20T10:00:00Z"}]})
        if "$filter=JoinWebUrl" in url:
            return FakeResponse({"value": [{"id": "meeting-1", "subject": "Ad-hoc Sync"}]})
        return FakeResponse({"id": "transcript-1"})

    monkeypatch.setattr(requests, "get", fake_get)

    transcript = provider.get_transcript(JOIN_URL, access_token="at-1")

    assert transcript.metadata["online_meeting_id"] == "meeting-1"
    assert transcript.meeting_title == "Ad-hoc Sync"


def test_speaker_attribution_denied_falls_back_to_unattributed_text(provider, monkeypatch):
    """SpeakerAttributionNotAllowed only affects VTT; the plain type must be retried."""
    attempts = []

    def fake_get(url, *args, **kwargs):
        headers = dict(kwargs.get("headers") or {})
        if url.endswith("/content"):
            attempts.append(headers.get("Accept"))
            if headers.get("Accept") == "text/vtt":
                return FakeResponse(
                    {"error": {"code": "Forbidden",
                               "message": "Speaker attribution is not allowed.",
                               "innerError": {"code": "SpeakerAttributionNotAllowed"}}},
                    status_code=403,
                )
            return FakeResponse(
                status_code=200,
                text="Support volume is up 30% this quarter.\nWe need email notifications.",
                headers={"Content-Type": "text/plain"},
            )
        return FakeResponse({"id": "transcript-1"})

    monkeypatch.setattr(requests, "get", fake_get)

    transcript = provider.get_transcript("meeting-1/transcripts/transcript-1", access_token="at-1")

    assert attempts == ["text/vtt", "application/vnd.microsoft.graph.transcript+text"]
    assert transcript.metadata["speaker_attributed"] is False
    assert transcript.metadata["content_format"] == "text/plain"
    assert transcript.participants == []
    assert "speaker_attribution_note" in transcript.metadata
    # The wording must survive verbatim so evidence validation can still match it.
    assert "Support volume is up 30% this quarter." in transcript.raw_text


def test_tenant_disabled_graph_transcript_access_is_reported_as_unavailable(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if url.endswith("/content"):
            return FakeResponse(
                {"error": {"code": "Forbidden",
                           "message": "Access to transcripts is disabled.",
                           "innerError": {"code": "GraphAccessToTranscriptsDisabled"}}},
                status_code=403,
            )
        return FakeResponse({"id": "transcript-1"})

    monkeypatch.setattr(requests, "get", fake_get)

    with pytest.raises(TranscriptUnavailableError, match="GraphAccessToTranscriptsDisabled"):
        provider.get_transcript("meeting-1/transcripts/transcript-1", access_token="at-1")


def test_other_403_is_reported_as_a_consent_problem(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if url.endswith("/content"):
            return FakeResponse(
                {"error": {"code": "Authorization_RequestDenied",
                           "message": "Insufficient privileges."}},
                status_code=403,
            )
        return FakeResponse({"id": "transcript-1"})

    monkeypatch.setattr(requests, "get", fake_get)

    with pytest.raises(ProviderConsentRequiredError, match="admin consent"):
        provider.get_transcript("meeting-1/transcripts/transcript-1", access_token="at-1")


def test_expired_meeting_transcript_lookup_is_reported(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if url.endswith("/transcripts"):
            return FakeResponse({"value": []})
        return FakeResponse({"value": []})

    monkeypatch.setattr(requests, "get", fake_get)

    with pytest.raises(TranscriptUnavailableError, match="never transcribed|expired"):
        provider.get_transcript("meeting-1", access_token="at-1")


def test_empty_transcript_content_is_reported(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        if url.endswith("/content"):
            return FakeResponse(status_code=200, text="WEBVTT\n\n",
                                headers={"Content-Type": "text/vtt"})
        return FakeResponse({"id": "transcript-1"})

    monkeypatch.setattr(requests, "get", fake_get)

    with pytest.raises(TranscriptUnavailableError, match="empty transcript"):
        provider.get_transcript("meeting-1/transcripts/transcript-1", access_token="at-1")


def test_graph_404_is_reported_as_an_api_error(provider, monkeypatch):
    monkeypatch.setattr(
        requests, "get",
        lambda *a, **kw: FakeResponse(
            {"error": {"code": "NotFound", "message": "The meeting does not exist."}},
            status_code=404,
        ),
    )

    with pytest.raises(ProviderAPIError, match="404"):
        provider.get_transcript("meeting-missing/transcripts/t-1", access_token="at-1")


def test_graph_network_error_is_reported(provider, monkeypatch):
    def boom(*args, **kwargs):
        raise requests.Timeout("read timed out")

    monkeypatch.setattr(requests, "get", boom)

    with pytest.raises(ProviderAPIError, match="Network error"):
        provider.get_transcript("meeting-1/transcripts/t-1", access_token="at-1")


# --- Refresh-and-retry against the real provider code path ---

def test_expired_token_triggers_refresh_then_succeeds(provider, monkeypatch):
    def fake_get(url, *args, **kwargs):
        headers = dict(kwargs.get("headers") or {})
        if headers.get("Authorization") == "Bearer stale-token":
            return FakeResponse(
                {"error": {"code": "InvalidAuthenticationToken",
                           "message": "Access token has expired."}},
                status_code=401,
            )
        if url.endswith("/content"):
            return FakeResponse(status_code=200, text=VTT_SAMPLE,
                                headers={"Content-Type": "text/vtt"})
        return FakeResponse({"id": "transcript-1"})

    monkeypatch.setattr(requests, "get", fake_get)

    class MockPost:
        status_code = 200
        def json(self):
            return {"access_token": "fresh-token", "expires_in": 3599}

    monkeypatch.setattr(requests, "post", lambda *a, **kw: MockPost())

    tokens = TokenSet.from_response({"access_token": "stale-token", "refresh_token": "rt-1"})
    transcript, updated = call_with_refresh(
        provider,
        tokens,
        lambda token: provider.get_transcript(
            "meeting-1/transcripts/transcript-1", access_token=token
        ),
    )

    assert updated.access_token == "fresh-token"
    assert updated.refresh_token == "rt-1"
    assert "Sarah Khan: Support volume is up 30% this quarter." in transcript.raw_text
